# Generated by Django 5.2.7 on 2025-10-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload a featured image for this post (optional)', null=True, upload_to='blog_images/'),
        ),
    ]
